src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\ExpressionValidator;

/**
 * @ORM\Entity(repositoryClass=SessionRepository::class)
 */
class Session
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime" ,nullable=true)
     */
    private $date_deb;

    /**
     * @ORM\Column(type="datetime",nullable=true)
     */
    private $date_fin;

    /**
     * @ORM\Column(type="datetime",nullable=true)
     */
    private $date_inscri_deb;

    /**
     * @ORM\Column(type="datetime",nullable=true)
     */
    private $date_inscri_fin;

    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    private $nbrePlaces;

    /**
     * @ORM\ManyToOne(targetEntity="Formation", inversedBy="sessions",cascade={"remove"})
     * @ORM\JoinColumn(name="formation_id", referencedColumnName="id")
     */
    private $formation;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     */
    private $adresse;

    // /**
    //  * @ORM\Column(type="datetime",options={"default": "CURRENT_TIMESTAMP"})
    //  */
    // private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="sessions")
     */
    private $users;


    public function __construct()
    {

        // $this->createdAt = new \DateTime();
        $this->date_deb = new \DateTime();
        //$this->formations = new ArrayCollection();
        $this->users = new ArrayCollection();
       
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDeb(): ?\DateTimeInterface
    {
        return $this->date_deb;
    }

    public function setDateDeb(\DateTimeInterface $date_deb): self
    {
        $this->date_deb = $date_deb;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getDateInscriDeb(): ?\DateTimeInterface
    {
        return $this->date_inscri_deb;
    }

    public function setDateInscriDeb(\DateTimeInterface $date_inscri_deb): self
    {
        $this->date_inscri_deb = $date_inscri_deb;

        return $this;
    }

    public function getDateInscriFin(): ?\DateTimeInterface
    {
        return $this->date_inscri_fin;
    }

    public function setDateInscriFin(\DateTimeInterface $date_inscri_fin): self
    {
        $this->date_inscri_fin = $date_inscri_fin;

        return $this;
    }

    public function getNbrePlaces(): ?int
    {
        return $this->nbrePlaces;
    }

    public function setNbrePlaces(int $nbrePlaces): self
    {
        $this->nbrePlaces = $nbrePlaces;

        return $this;
    }

    public function getFormation(): ?Formation
    {
        return $this->formation;
    }

    public function setFormation(?Formation $formation): self
    {
        $this->formation = $formation;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    // public function getCreatedAt(): ?\DateTimeInterface
    // {
    //     return $this->created_at;
    // }

    // public function setCreatedAt(\DateTimeInterface $created_at): self
    // {
    //     $this->created_at = $created_at;

    //     return $this;
    // }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
        }

        return $this;
    }

    public function __toString() {
        return $this->id;
    }





 
}

src/Form/SessionType.php
<?php

namespace App\Form;

use App\Entity\Session;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\ButtonType;


class SessionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('date_inscri_deb', DateTimeType::class, [
            'label'=> 'Debut d\'inscription* :',
            'widget' => 'single_text',
            'empty_data' => null,
            'required' => false,
            // 'input'  => 'datetime_immutable',

            'attr' => ['class' => 'js-datepicker form-control inscrideb','id'=>'date_inscri_deb','style'=>'width:45%'
         ],
        ])
        ->add('date_inscri_fin', DateTimeType::class, [
            'label'=> 'Fin d\'inscription* :',
            'widget' => 'single_text',
            // 'input'  => 'datetime_immutable',
            'empty_data' => null,
            'required' => false,
            // adds a class that can be selected in JavaScript
            'attr' => ['class' => 'js-datepicker form-control inscrifin','style'=>'width:89%'
            ],
        ])
        ->add('nbrePlaces' ,NumberType::class, [
            'label'    => 'Nombre de places* :',
            'required' => false,
            'empty_data' => null,
            'attr' => [
                'placeholder' => '',
                'class' => 'form-control',
                'id'=>'nbrePlaces',
                'style' => ' border: 1px solid #ced4da;
                border-radius: .25rem; width: 95%;
                margin-left: 1%;'
            ]
            ])

        ->add('date_deb', DateTimeType::class, [
            'label'=> 'Début de session* : ',
            'widget' => 'single_text',
            'required' => false,
            // 'input'  => 'datetime_immutable',
            'empty_data' => null,
            // adds a class that can be selected in JavaScript
            'attr' => ['class' => 'js-datepicker form-control deb','id'=>'date_deb','style'=>'width:45%'
            ],
        ])
        ->add('date_fin', DateTimeType::class, [
            'label'=> 'Fin de session* : ',
            'widget' => 'single_text',
            'required' => false,
            // 'input'  => 'datetime_immutable',
            'empty_data' => null,
            // adds a class that can be selected in JavaScript
            'attr' => ['class' => 'js-datepicker form-control fin','id'=>'date_fin','style'=>'width:89%'
            ],
        ])
   

        ->add('adresse', TextType::class, [
            'label' => 'Adresse* :',
            'required' => false,
            'empty_data' => '',
            'attr' => [
                'placeholder' => '',
                'class' => 'form-control',
                'id'=>'adresse',
                'style' => ' border: 1px solid #ced4da;
                border-radius: .25rem; width: 95%;
                margin-left: 1%;margin-bottom:2%'
            ]
        ])
      
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Session::class,
        ]);
    }
}

src/Controller/SessionController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use App\Entity\Session;
use App\Repository\SessionRepository;
use App\Data\SearchData;
use App\Form\SearchSessionType;
use App\Form\InscriptionType;
class SessionController extends AbstractController
{
    /**
     * @Route("/session", name="session")
     */
    public function index(TokenStorageInterface $tokenStorage,SessionRepository $repository,Request $request)
    {
        $user = $tokenStorage->getToken()->getUser();
        $data = new SearchData();
        $data->page = $request->get('page', 1);
        $form = $this->createForm(SearchSessionType::class, $data);
        $form->handleRequest($request);
        $session = $repository->findSearch($data,'validée');
           
        
        return $this->render('session/index.html.twig', [
            'user' => $user,'session'=>$session,'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/incription/{id}", name="inscrire")
     */
    public function inscire($id,TokenStorageInterface $tokenStorage,SessionRepository $repository,Request $request)
    {
        $user = $tokenStorage->getToken()->getUser();
        $s = $this->getDoctrine()->getRepository(Session::class)->find($id);
        if (!$s->getUsers()->contains($user) and $s->getNbrePlaces()>0) { 
       
            $s->addUser($user);

        
        $s->setNbrePlaces($s->getNbrePlaces()-1);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($s);
         $entityManager->persist($user);
        $entityManager->flush();
        $this->addFlash('notice', 'Vous etes inscris');
        }else{
            $this->addFlash('notice', 'Vous etes déjà inscris. ');
        }

        
        return $this->redirectToRoute('session', ['user'=>$user]);
        

       
        
    }
}

templates/session/index.html.twig
{% extends 'baseHome.html.twig' %}

{% block title %}Sessions
{% endblock %}

{% block body %}


	<div class="admin">
		<div class="breadcrumbs_container">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="breadcrumbs">
							<ul>
								<li>
									<a href="index.html">Home</a>
								</li>
								<li>Courses</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="container">
		<div
			class="row">


			<!-- Courses Main Content -->
			<div class="col-lg-12">
				<div class="courses_search_container" style="margin-top:2%">
					{% include 'filterSession.html.twig' with {form:form} only %}
				</div>
				<br>
				{%for message in app.flashes('notice')%}
					<div class="alert alert-success text-center">
						{{message}}
					</div>
					{%endfor%}

					<div class="courses_container">
						<div
							class="row courses_row">

							<!-- Course -->
							<div class="col-lg-12 course_col">
								<div class="tabs d-flex flex-row align-items-center justify-content-start">
									<div class="tab active">Sessions</div>
								</div>
								<div
									class="tab_panels">

									<!-- Description -->
									{% for s in session %}
										<div class="tab_panel active" >
											<p>Prévue le :</p>
											<div class="row">

												<div class="col row" style="max-width:fit-content;">

													<div class="col" style="max-width:min-content;">
														<div class="tab_panel_title">{{s.dateDeb|date('d') }}</div>
													</div>
													<div class="row">
														<div class="col">
															<div class="tab_panel_title" id="mois">{{s.dateDeb|format_date('MMM', 'fr', 'Europe/Paris', constant('IntlDateFormatter::LONG')) }}</div>
															<div class="tab_panel_title" id="year">{{s.dateDeb|date('Y') }}</div>
														</div>
													</div>

												</div>
												<div class="tab_panel_content col" style="text-align:center">
													<div class="tab_panel_text">
														<h5>
															<a style="color:#384158;" href="{{path('detail',{ 'id': s.formation.id })}}">{{s.formation.title}}</a>
														</h5>
														{% if s.dateDeb|date('d') == s.dateFin|date('d') %}
															<h5>Durée:
																{{s.dateDeb|date('H:i')}}
																-
																{{s.dateFin|date('H:i')}}</h5>
														{% else %}
															<h5>
																jusqu'à
																{{s.dateFin|format_date(null, 'fr', 'Europe/Paris', constant('IntlDateFormatter::LONG')) }}</h5>
														{% endif %}
													</div>


												</div>
												<div class="tab_panel_content col">
													<div class="tab_panel_text">
														<h5>Nombre de places disponibles:
															<span style="color: #76777a;">{{s.nbrePlaces}}</h5>
															<p>{{s.adresse}}</p>
															{# {% if is_granted('ROLE_ADMIN') or s.formation in app.user.formation %}
																<button type="submit" class="btn btn-outline-info" style="color:rgb(76, 224, 228);float: right;    margin-right: 3%;
																	    margin-bottom: 3%;" data-toggle="modal" data-target="#exampleModal">
																	<a style="color:rgb(76, 224, 228)" onmouseover="this.style.color='white'" onmouseout="this.style.color='rgb(76, 224, 228)';">
																		liste des inscrits</a>
																</button>
															{% endif %} #}
															{% if s.nbrePlaces > 0 %}

																<button type="submit" class="btn btn-outline-info" style="color:rgb(76, 224, 228);float: right;margin-right:1%" onmouseover="this.style.color='white'" onmouseout="this.style.color='rgb(76, 224, 228)';">
																	<a style="color:rgb(76, 224, 228);" onmouseover="this.style.color='white'" onmouseout="this.style.color='rgb(76, 224, 228)';" href="{{path('inscrire',{ 'id': s.id })}}">
																		Inscrire</a>
																</button>

															{% else %}
																<p style="float:right">Le nombre de places est saturé.</p>
																<p>
																{% endif %}
															</div>


														</div>
													</div>
												</div>
												
												

										


										
<br>
									{% endfor %}
								</div>
							</div>
</div>	</div>
						</div>


					</div>
					<div class="row pagination_row">
						<div class="col">
							<div class="pagination_container d-flex flex-row align-items-center justify-content-start"></div>
							{{ knp_pagination_render(session) }}
						</div>
					</div>
				</div>
			</div>
		</div>

	</div>
</div></div></div><div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"><div class="modal-dialog" role="document">
<div class="modal-content">
	<div class="modal-header">
		<h6 class="text-center" id="exampleModalLabel" style='font-family: Roboto Slab, serif;font-size: x-large;'>Inscription</h6>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
	<div class="modal-body">

		<div class="sticky-top">


			<table class="table">
				<thead style="background-color:rgb(76, 224, 228);">
					<tr>

						<th scope="col" style='color: white;font-family: Roboto Slab, serif;'>Email</th>
						<th scope="col" style='color: white;font-family: Roboto Slab, serif;'>Nom</th>

					</tr>
				</thead>
				<tbody>
					{% for s in session %}
						{% for u in s.users %}
							<tr>

								<td style="font-family: 'Roboto Slab', serif;color: #384158;">{{u.email}}</td>
								<td style="font-family: 'Roboto Slab', serif;color: #384158;">{{u.name}}</td>

							</tr>
						{% endfor %}
					{% endfor %}

				</tbody>
			</table>


		</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>


	</div>

</div></div></div>{% endblock %}{% block javascripts %}{{parent()}}<script>$('.js-datepicker').datepicker({format: 'yyyy.MM.dd'});</script>{% endblock %}